cfn.yaml, src/main/scala/payment_failure_comms/SalesforceConnector.scala, src/main/scala/payment_failure_comms/models/Config.scala, src/main/scala/payment_failure_comms/models/Failure.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecord.scala, src/main/scala/payment_failure_comms/models/SFCompositeResponse.scala, src/main/scala/payment_failure_comms/models/SalesforceAuth.scala, src/test/scala/payment_failure_comms/IdapiConnectorTest.scala, src/test/scala/payment_failure_comms/SalesforceConnectorTest.scala, src/test/scala/payment_failure_comms/testData/ConnectorTestData.scala
Add a Salesforce Connector, Salesforce connection related failure classes and Salesforce secrets config/logic to the repo.
IDAPI test data was moved into more abstract object so it can be unit by any Connector's uni tests.
=> SalesforceConnector

cfn.yaml, src/main/scala/payment_failure_comms/BrazeConnector.scala, src/main/scala/payment_failure_comms/Handler.scala, src/main/scala/payment_failure_comms/IdapiConnector.scala, src/main/scala/payment_failure_comms/SalesforceConnector.scala, src/test/scala/payment_failure_comms/IdapiConnectorTest.scala, src/test/scala/payment_failure_comms/testData/ConnectorTestData.scala
Makes a number of small fixes to the code and standardises some pieces of logic and variable names across the codebase.
Summary:
- Standardises Connector related language used
- Fixes issue with getting the body from `ResponseBody` (`.body().string()` can only be used once)
- Fixes IDAPI related variable names in CloudFormation 
- Alters the handler to enable testing of the environment variables
- Improvements to consistency in the code base
=> Fixes and tweaks

src/main/scala/payment_failure_comms/BrazeConnector.scala, src/main/scala/payment_failure_comms/Handler.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecordUpdate.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecordWithBrazeId.scala, src/main/scala/payment_failure_comms/models/brazeTrackEvents.scala
This change fixes a bug where payment-failure records that had no matching Braze ID were being written back to Salesforce as successes.  It also does some refactoring of some of the processing to keep a clear distinction between the two types of record: those with a Braze ID and those without.
There will be an improvement following, to log cases where Idapi fails.
=> Fix writing back to Salesforce and refactor

src/main/scala/payment_failure_comms/BrazeConnector.scala, src/main/scala/payment_failure_comms/Handler.scala, src/main/scala/payment_failure_comms/models/BrazeUserData.scala, src/main/scala/payment_failure_comms/models/brazeTrackEvents.scala, src/test/scala/payment_failure_comms/models/BrazeTrackRequestTest.scala
This change ensures that we don't write duplicate custom events to Braze.
For each relevant payment-failure record in Salesforce, we check for corresponding events in Braze before writing them.
The response from Braze doesn't tell us the properties of events.  It just tells us event names and the first and last dates that they occurred.  From this, we can say that an event with the same name as an existing event on the same account shouldn't be written to the account if the existing event has the same or later date than the event we're considering writing.
The scenario in which we could get duplicate events is:
1. Read payment-failure records from Salesforce is successful
2. Write events to Braze is successful
3. Write results back to Salesforce fails
In this scenario, on the next attempt …
=> Read Braze events before writing them

src/main/scala/payment_failure_comms/SalesforceConnector.scala, src/main/scala/payment_failure_comms/models/EventTime.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecord.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecordUpdate.scala, src/main/scala/payment_failure_comms/models/brazeTrackEvents.scala, src/test/scala/payment_failure_comms/models/BrazeTrackRequestTest.scala
As a result of guardian/salesforce#499, we no longer need to use the `Status__c` field, as `PF_Comms_Status__c` has all the data needed to decide what to send to Braze.
This change replaces all the uses of `Status__c` and uses the new list of possible values for `PF_Comms_Status__c`.
=> Use new status values

.github/workflows/ci.yml, project/plugins.sbt
This adds a check during CI that all production, test and SBT config files are formatted according to the scalafmt [config rules](https://github.com/guardian/payment-failure-comms/blob/main/.scalafmt.conf).
See https://scalameta.org/scalafmt/docs/installation.html#task-keys
=> Check formatting during CI

README.md, cfn.yaml, src/main/scala/payment_failure_comms/Handler.scala, src/main/scala/payment_failure_comms/Log.scala
This adds an alarm that will go off a minute after any lambda failure in the Prod environment.
Once we have gathered some reasons for it going off, we can tweak the alarm threshold and build up the troubleshooting steps in the Readme.
Tested in Dev.
=> Set off alarm on lambda failure

cfn.yaml, src/main/scala/payment_failure_comms/TestEventLoader.scala, src/main/scala/payment_failure_comms/models/Config.scala
Some configuration has been renamed to follow conventions.
* We name secrets in Secrets Manager in format `stage/system/optional subsystem/name` and the code has been changed to reflect this
* Prod settings have been updated to real names
* Braze has `Dev` and `Live` stages so the code has been changed to reflect this
* The Braze bearer token is referred to as an API key in Braze itself.
=> Refactor configuration

src/main/scala/payment_failure_comms/models/BrazeUserData.scala, src/main/scala/payment_failure_comms/models/brazeTrackEvents.scala, src/test/scala/payment_failure_comms/models/BrazeTrackRequestTest.scala
The response from Braze to a `/users/export/ids` request has an optional `custom_events` field which we have modelled as a required field.  This change corrects that by making the field optional and then modifying the use of it to find the diff with a given collection of incoming `CustomEvent`s.
=> Support optional custom_events field in Braze /users/export/ids response

src/main/scala/payment_failure_comms/SalesforceConnector.scala
This reduces the number of payment-failure records we read from Salesforce to 50 as that is the update limit for a single request in Braze.
It would be possible to fetch more and process them in multiple writes to Braze but that would add complexity to the code.  So keeping it simple and just reading from Salesforce more often.
=> Avoid Braze concurrent update limit

cfn.yaml
This enables the lambda to run in Prod every 20 mins.
I've increased the number of runs as we now read fewer in a batch because of #64.
Lambdas automatically retry twice on failure but I've disabled that as we are running every 20 mins anyway.
=> Enable scheduled run in Prod

src/main/scala/payment_failure_comms/Handler.scala, src/main/scala/payment_failure_comms/SalesforceConnector.scala, src/main/scala/payment_failure_comms/models/PaymentFailureRecord.scala, src/test/scala/payment_failure_comms/models/BrazeTrackRequestTest.scala
There are many contact records in Salesforce without Identity IDs so we can't assume that it will be there.
This change makes the field optional and there is a change to the logic of determining the Braze account ID from the contact.  Where the contact has no Identity ID we use the ID of the contact record as the Braze account ID.  This matches existing accounts in Braze because it's an established pattern for dealing with cases where there's no Identity ID to match on.
=> Support contact records with no Identity ID

src/main/scala/payment_failure_comms/BrazeConnector.scala, src/main/scala/payment_failure_comms/HttpClient.scala, src/main/scala/payment_failure_comms/IdapiConnector.scala, src/main/scala/payment_failure_comms/SalesforceConnector.scala
We were seeing occasional timeout errors reading from Salesforce.
So this increases connection and read timeouts from the default 10 s to 30 s.
=> Increase connect timeout to 30 s

src/main/scala/payment_failure_comms/SalesforceConnector.scala
The query was filtering on a formula field, which was performing badly and creating timeouts on the client.
Now it filters on another non-formula field first, `Status_Helper__c`, which means that the formula field has only to apply to a restricted subset of the table.  This appears to at least halve the duration of the query in the Salesforce console.
Works in Code.
=> Optimise filter on Salesforce read query

cfn.yaml
To trigger alarm after 3 failures per hour rather than one.
This is because we're seeing occasional timeouts but the read always succeeds eventually.
=> Increase alarm threshold

.github/workflows/ci.yml
This should skip the CI workflow when a PR is raised from a fork.
Inspecting the content of the `github` object, `github.event.pull_request.head.repo.owner.login` seems to be the most obvious identifier of the source repo.
=> Tighten conditions for running CI workflow

.github/workflows/ci.yml
We need to include the PR event as part of the condition, otherwise a push to main will also be seen as a PR from a forked repo.
=> Correct isPrFromForkedRepo condition

src/main/scala/payment_failure_comms/models/PaymentFailureRecord.scala, src/main/scala/payment_failure_comms/models/brazeTrackEvents.scala, src/test/scala/payment_failure_comms/models/BrazeTrackRequestTest.scala
Although the product name should always have a value, that can't be relied on as there are several cases where subscriptions have no product name.  Rather than clean up all the data and the generating code in Salesforce, it will be easier to make the field optional in the model here.
Because we export the records in a single structure, if a single one fails to be deserialised there will be an ever-growing buildup so even though this is a very rare occurrence it will block the whole system.
=> Make product name optional in model

src/main/scala/payment_failure_comms/SalesforceConnector.scala
This is to ensure that any backlog is cleared in the right order.
I see that there are still some to clear from 21 Feb.
=> Order payment-failure records by invoice date

cfn.yaml
The longest run in the past 24 hours took 33 seconds so it seems safe to temporarily increase to run every minute.
Then will switch back to run every 20 minutes when the backlog is clear.
=> Speed up backlog clearance

cfn.yaml
It's very strict about singulars and plurals.
See https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
=> Correct rate expression

cfn.yaml
Kelvin attempted to process all records which did not get through to Braze between 22/03/2022 and 01/04/2022. This attempt to clear the backlog did not process the records correctly and they did not reach Braze. The issue was due to `PF_Comms_Number_of_Attempts__c` field reaching the maximum of 5 and therefore these records were not being retrieved when running the lambda.
To fix this, this field was updated to 4 on 3905 records so they can now be processed by the lamba. Around 1000 of these records have already been recovered or cancelled, meaning the lambda should process approximately 3000 records from this backlog.
=> Speed up backlog clearance, run lambda every minute

cfn.yaml
The lambda has finished processing the 3000 records from the backlog so we're putting the lambda back to it's usual schedule.
=> Put lambda back to normal schedule

cfn.yaml
As the payment failure period is 29 days it's useful to have records from further back than that.
This makes it easier to troubleshoot problems.
The storage of logs is cheap and there is no particularly sensitive data in the log.
=> Retain logs for 90 days

cfn.yaml
This lambda is not intended to retry, but we've found that it is retrying due to the default EventInvokeConfig (asynchronous invocation) retry value of 2. This adds the explicit EventInvokeConfig to the cfn file with a retry limit of 0.
=> Set asynchronous invocation retries to zero

cfn.yaml
This PR makes it so that 3 failures in a row (every 20 mins) won't sound an alarm - actually it will need 5 failures in a row.
I've also tweaked the alarm names and description to be a bit clearer.
=> require 5 failures in a row to cause an alarm

README.md, cfn.yaml
It's been observed that the causes of many individual failures are typically due to the state of the user account rather than issues in the code, such as instances where a customer may have deleted their identity account.
By increasing the threshold of the FailureLimitReachedAlarm, we hope to reduce the number of false positives, ensuring that the alarm is only triggered when there is a probable issue with our code and not due to individual account states.
=>  Increase FailureLimitReachedAlarm Threshold 

build.sbt
we need the latest version of netty to avoid https://github.com/advisories/GHSA-4g8c-wm8x-jfhw
=> update AWS SDK v2 to latest
